theme: jekyll-theme-slate

title: Cognitive Foundry
project_title: Cognitive Foundry

twitter_username: AlgoFoundry
github_username: algorithmfoundry

repository_url: https://github.com/algorithmfoundry/Foundry
