theme: jekyll-theme-slate

title: Cognitive Foundry
project_title: Cognitive Foundry

twitter_username: AlgoFoundry
github_username: algorithmfoundry

site.github.repository_url: https://github.com/algorithmfoundry/Foundry

site.github.is_user_page: true
site.github.is_project_page: false

github:
  repository_url: https://github.com/algorithmfoundry/Foundry
