theme: jekyll-theme-slate

title: Cognitive Foundry
project_title: Cognitive Foundry

twitter_username: AlgoFoundry
github_username: algorithmfoundry

github:
  repository_url: https://github.com/algorithmfoundry/Foundry
  is_user_page: true
  is_project_page: false
